version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 18
        commands:
            - echo "installing packages..."
            - npm i
    pre_build:
        commands: 
            - echo "Tests passed successfully."
    build:
        commands:
            - echo "Build passed successfully."
            - npm run build
            - zip -r source.zip build/
    post_build:
        commands:
            - echo "Post build successful"

artifacts:
  files:
    - '**/*'
  name: deploy-nodejs-build-artifacts
